version: '3.8'

services:
  oracle-db:
    build: ./oracle-db
    container_name: oracle-db
    environment:
      - ORACLE_PWD=140204
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always

  app:
    build: .
    container_name: gs-java-app
    depends_on:
      - oracle-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=140204
    ports:
      - "8080:8080"
    restart: always

volumes:
  oracle-data: 